######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 13 15:43:11 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += declarativeobjects_p.h declarativewidgetdocument.h
SOURCES += declarativeobjects.cpp declarativewidgetdocument.cpp main.cpp

QT += declarative
