# SPDX-FileCopyrightText: 2025 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

name: CI Qt 6

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-15
        preset:
          - dev6
          - rel6

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          cache: true

      - name: Install dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update -qq
          sudo apt install xvfb

      - name: Install ninja-build tool (must be after Qt due PATH changes)
        if: ${{ runner.os != 'macOS' }}
        uses: turtlesec-no/get-ninja@main

      - name: Install ninja-build tool (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: brew install ninja

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Make sure MSVC is found when Ninja generator is in use
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build project (cmake)
        run: |
          cmake --preset=${{ matrix.preset }} .
          cmake --build build-${{ matrix.preset }}

      - name: Run tests (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: xvfb-run ctest --test-dir ./build-${{ matrix.preset }} --verbose --output-on-failure
        env:
          DISPLAY: ":0"

      # these fail, need more investigation. Likely just a CI setup problem
      # - name: Run tests (macOS/Windows)
      #   if: ${{ runner.os != 'Linux' }}
      #   run: ctest --test-dir ./build-${{ matrix.preset }} --verbose --output-on-failure
